In [1]:
import pandas as pd
import numpy as np
import pandas as pd
df_train = pd.read_csv("train.csv") 
df_train.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

In [2]:
dix = pd.DatetimeIndex(df_train.datetime)

df_train['hour']=pd.DatetimeIndex(df_train.datetime).hour
df_train['day']=pd.DatetimeIndex(df_train.datetime).dayofweek  #自己转换成星期
df_train['month']=pd.DatetimeIndex(df_train.datetime).month

df_train.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,hour,day,month
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16,0,5,1
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40,1,5,1
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32,2,5,1
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13,3,5,1
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1,4,5,1

In [3]:
df_train.corr()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,hour,day,month
season,1.000000,0.029368,-0.008126,0.008879,0.258689,0.264744,0.190610,-0.147121,0.096758,0.164011,0.163439,-0.006546,-0.010553,0.971524
holiday,0.029368,1.000000,-0.250491,-0.007074,0.000295,-0.005215,0.001929,0.008409,0.043799,-0.020956,-0.005393,-0.000354,-0.191832,0.001731
workingday,-0.008126,-0.250491,1.000000,0.033772,0.029966,0.024660,-0.010880,0.013373,-0.319111,0.119460,0.011594,0.002780,-0.704267,-0.003394
weather,0.008879,-0.007074,0.033772,1.000000,-0.055035,-0.055376,0.406244,0.007261,-0.135918,-0.109340,-0.128655,-0.022740,-0.047692,0.012144
temp,0.258689,0.000295,0.029966,-0.055035,1.000000,0.984948,-0.064949,-0.017852,0.467097,0.318571,0.394454,0.145430,-0.038466,0.257589
atemp,0.264744,-0.005215,0.024660,-0.055376,0.984948,1.000000,-0.043536,-0.057473,0.462067,0.314635,0.389784,0.140343,-0.040235,0.264173
humidity,0.190610,0.001929,-0.010880,0.406244,-0.064949,-0.043536,1.000000,-0.318607,-0.348187,-0.265458,-0.317371,-0.278011,-0.026507,0.204537
windspeed,-0.147121,0.008409,0.013373,0.007261,-0.017852,-0.057473,-0.318607,1.000000,0.092276,0.091052,0.101369,0.146631,-0.024804,-0.150192
casual,0.096758,0.043799,-0.319111,-0.135918,0.467097,0.462067,-0.348187,0.092276,1.000000,0.497250,0.690414,0.302045,0.246959,0.092722
registered,0.164011,-0.020956,0.119460,-0.109340,0.318571,0.314635,-0.265458,0.091052,0.497250,1.000000,0.970948,0.380540,-0.084427,0.169451
count,0.163439,-0.005393,0.011594,-0.128655,0.394454,0.389784,-0.317371,0.101369,0.690414,0.970948,1.000000,0.400601,-0.002283,0.166862
hour,-0.006546,-0.000354,0.002780,-0.022740,0.145430,0.140343,-0.278011,0.146631,0.302045,0.380540,0.400601,1.000000,-0.002925,-0.006818
day,-0.010553,-0.191832,-0.704267,-0.047692,-0.038466,-0.040235,-0.026507,-0.024804,0.246959,-0.084427,-0.002283,-0.002925,1.000000,-0.002266
month,0.971524,0.001731,-0.003394,0.012144,0.257589,0.264173,0.204537,-0.150192,0.092722,0.169451,0.166862,-0.006818,-0.002266,1.000000

In [42]:
df_train_target = df_train['count'].values
df_train_data = df_train[['hour','temp','atemp','humidity','season']].values
#'humidity' 'humidity','season'

In [43]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn import model_selection  
from sklearn import svm
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import learning_curve
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import explained_variance_score

import warnings
warnings.filterwarnings('ignore')

In [44]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle=True)

In [45]:
print("岭回归")    
for train, test in kf.split(df_train_data):    
    ridgeModel = linear_model.Ridge().fit(df_train_data[train], df_train_target[train])
    print("train score: {0:.3f}, test score: {1:.3f}\n".format(
        ridgeModel.score(df_train_data[train], df_train_target[train]), 
        ridgeModel.score(df_train_data[test], df_train_target[test])))
    #{0:.3f} 0表示第一个参数，保留三位小数，是训练集上的得分
    #{1:.3f} 1表示测试集上的得分

岭回归
train score: 0.333, test score: 0.342

train score: 0.339, test score: 0.321

train score: 0.334, test score: 0.341

train score: 0.339, test score: 0.320

train score: 0.332, test score: 0.350

In [12]:
print("支持向量回归/SVR(kernel='rbf',C=10,gamma=.001)")
for train, test in kf.split(df_train_data):
    
    svmModel = svm.SVR(kernel ='rbf', C = 10, gamma = .001).fit(df_train_data[train], df_train_target[train])
    print("train score: {0:.3f}, test score: {1:.3f}\n".format(
        svmModel.score(df_train_data[train], df_train_target[train]), 
        svmModel.score(df_train_data[test], df_train_target[test])))

支持向量回归/SVR(kernel='rbf',C=10,gamma=.001)
train score: 0.393, test score: 0.415

train score: 0.395, test score: 0.398

train score: 0.400, test score: 0.369

train score: 0.386, test score: 0.415

train score: 0.402, test score: 0.369